"""add last_opened_at to conversations

Revision ID: 49125c2736be
Revises: 8ffcbc43c71b
Create Date: 2026-07-09 12:58:24.938656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49125c2736be'
down_revision: Union[str, Sequence[str], None] = '8ffcbc43c71b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('last_opened_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'last_opened_at')
    # ### end Alembic commands ###
