"""add is_pinned and is_archived to workspaces

Revision ID: 4efe83411933
Revises: 9ca3c0fbf390
Create Date: 2026-06-24 21:44:30.295080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4efe83411933'
down_revision: Union[str, Sequence[str], None] = '9ca3c0fbf390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'workspaces',
        sa.Column('is_pinned', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'workspaces',
        sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.false()),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'is_archived')
    op.drop_column('workspaces', 'is_pinned')
    # ### end Alembic commands ###
